### ISSUE TITLE
Deploy matrix server

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-cluster#1553]
# Details

**Describe the solution you'd like:**

Deploy a matrix server

Depends on https://github.com/onedr0p/home-cluster/issues/1551

**Comment by rwaltr** [comment]
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.stack.imgur.com%2FUAxa8.gif&f=1&nofb=1)

**Comment by onedr0p** [comment]
Long lived issue, going to close this and revisit in the future
