### ISSUE TITLE
Trafik Pilot Token not encrypted

### ISSUE THREAD

**Issue by divialth** [onedr0p/home-cluster#1569]
You currently have stored the token for traefik pilot unencrypted in your repo. 
Wouldn’t it be better to SOPS encrypt it?
At least as far as I know this is a personal token. 

https://github.com/onedr0p/home-cluster/blob/33477a77667c8c769ee522fe96aa010816e226d4/cluster/apps/networking/traefik/helm-release.yaml#L73

**Comment by onedr0p** [comment]
From what I can tell it's not really sensitive information or at least something I can about being exposed if someone wants to add their traefik instance to my dashboard let them ;)

**Comment by divialth** [comment]
ok, i have thought this would "overwrite" your instance in your pilot dashboard, because only one could be connected with the same token.
But if this is not the case, feel free to close this issue :smile:

**Comment by onedr0p** [comment]
I am not sure... but thanks for your concern
