### ISSUE TITLE
How do you create secret variable?

### ISSUE THREAD

**Issue by budimanjojo** [onedr0p/home-cluster#1663]
# Details

**Ask your question:**
Hello, I really love your works and I want to base off your repo to get my own cluster organized :)
I have a question, how do you make those secret environments work? I see there's a `cluster-secrets` secret manifest in your `cluster-setting.yaml` file but I really can't figure how do you make it work, for example you have this line in your traefik deployment yaml:
```
annotations:        external-dns.alpha.kubernetes.io/hostname: "ipv4.${SECRET_DOMAIN}"
```
Thanks before :)

**Comment by onedr0p** [comment]
This is a feature of Flux that uses SOPS to do variable substitution 

See here https://github.com/k8s-at-home/template-cluster-k3s

**Comment by budimanjojo** [comment]
> This is a feature of Flux with SOPS that allows variable substitution
> 
> See here https://github.com/k8s-at-home/template-cluster-k3s

Yeah I found out about the fluxcd built-in envsubst, super cool stuff. Thanks for the link, a lot of things to learn all in once :D
