### ISSUE TITLE
Create Ansible task to clean up images on nodes

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-cluster#653]
# Details

**Describe the solution you'd like:**

Using the Ansible module, create a task to clean up stale container images using cron.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html

```bash
/usr/local/bin/k3s crictl rmi --prune > /dev/null 2>&1
```

**Anything else you would like to add:**

I am getting rook-ceph warnings in alert-manager about low disk space on my OS partition.

k3s-io/k3s#1900

**Comment by onedr0p** [comment]
I think this was resolved on rook's end. Closing

**Comment by reefland** [comment]
Q - did this work for your long term?  I had `--kubelet-arg=image-gc-high-threshold=65 --kubelet-arg=image-gc-low-threshold=50` set in my k3s parameters and disk space filled up to 86% and luckily ZFS sent me warning messages.

So I tried the `k3s crictl rmi --prune` which did clean up a lot of images, dropped me down to 34% capacity.

But I noticed it definitely removed images that were in use such as the pause image.  I manually pulled that back down:

```
sudo crictl pull k8s.gcr.io/pause:3.5
```

I was wondering if this process was too aggressive?

**Comment by onedr0p** [comment]
I never changed the kubelet args and just use whatever the default is. I also don't use a script on a cron to clean up stale images nor had an issue running the command and having it delete containers in use.

I do use a simple bash script to clean them up manually once in awhile, but I only run it when I'm bored 😂

I'm not sure, what the solution would be for you.

**Comment by reefland** [comment]
I was looking for a script that would delete all but 1 copy of the image, leaving the latest semantic version of the image if used or not.  Really just want to reduce history of images vs deleting every unused image.  

I noticed the self-hosted renovate image is 1.5GB in size and that updated nearly every night.  Pretty much where the bulk of my desk space went. 

Thank for the reply.  It's appreciated.
